config/routes.rb
Rails.application.routes.draw do
  resources :bookings do
    get :search , on: :collection
    member do
      get 'book'
      get 'amount'
    end
  end
  devise_for :users
  resources :categories
  resources :rooms
  root 'bookings#index'

  namespace :api do
    namespace :v1 do
      get "availability" => "bookings#availability"
      get "book_info" => "bookings#book_info"
    end
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < Api::V1::BaseController
  # before_filter :restrict_access
  # skip_before_filter  :verify_authenticity_token
  
  # API which shows availability of room by passing booking date and or room type
  def availability
    if params[:room_type].present? || params[:start_date].present? || params[:end_date].present?
      
      @bookings = Booking.all
      @cat = Category.all
      category_id = Category.find_by_name(params[:room_type]).id if params[:room_type].present?
      if @bookings.present?
        if @bookings
          ids = @bookings.pluck(:room_id)
          date1 = params[:start_date].to_date if params[:start_date].present?
          @start_date = date1.strftime("%Y %d %m") if date1.present?
          date2 = params[:end_date].to_date if params[:end_date].present?
          @end_date = date2.strftime("%Y %d %m") if date2.present?

          if category_id.present? and params[:start_date].present? and params[:end_date].present?

            bookings = Booking.where("category_id = ? and start_date <= ? OR end_date >= ?", category_id, @start_date,@end_date).pluck(:room_id)

            @rooms = Room.where("category_id = ?  and id NOT IN (?) ",category_id,bookings)
            if @rooms.present?
              render json: {message: "Available!", rooms: @rooms,  status: 200}
            else
              render json: {message: "No Rooms found", status: 406}
            end

          elsif category_id.present? and params[:start_date].present? 
            
            bookings = Booking.where("category_id = ? or start_date = ? ", category_id, @start_date).pluck(:room_id)
            @rooms = Room.where("category_id = ?  and id NOT IN (?) ",category_id,bookings)
            if @rooms.present?
            render json: {message: "Available!", rooms: @rooms,  status: 200}
            else
              render json: {message: "No Rooms found", status: 406}
            end

          elsif category_id.present? and params[:end_date].present? 
            
            bookings = Booking.where("category_id = ? or end_date = ? ", category_id, @end_date).pluck(:room_id)
            @rooms = Room.where("category_id = ?  and id NOT IN (?) ",category_id,bookings)
            if @rooms.present?
            render json: {message: "Available!", rooms: @rooms,  status: 200} 
            else
              render json: {message: "No Rooms found", status: 406}
            end

          elsif category_id.present? 
            @rooms = Room.where(category_id: category_id)
            if @rooms.present?
            render json: {message: "Available!", rooms: @rooms,  status: 200}
            else
              render json: {message: "No Rooms found", status: 406}
            end
          
          elsif params[:start_date].present?
             # redirect_to request.referer, notice: 'Please Select End Date'
             render json: {message: "Please Select End Date",  status: 404}
          elsif params[:end_date].present?
              # redirect_to request.referer, notice: 'Please Select Start Date'
              render json: {message: "Please Select Start Date", status: 404}
          else
            render json: {message: "Please Select Date", status: 404}
          end
        end
      else
        category = Category.find(category_id)
        @rooms = category.rooms
        if @rooms.present?
          render json: {message: "Available!", rooms: @rooms,  status: 200}
        else
              render json: {message: "No Rooms found", status: 406}
        end
      end
    else
      render json: {message: "Invalid call. Missing parameters.", status: 406}
    end
  end

  # API shows booked room and booking information
  def book_info
    if params[:user_id].present?
      @booking_info = Booking.where("user_id = ?",params[:user_id])
      @rooms = Room.where("id IN (?)", @booking_info.pluck(:room_id))
      if @booking_info.present? and @rooms.present?
        render :book_info 
      else
        render json: {message: "No Bookings found", status: 406}
      end
    else
      render json: {message: "Invalid call. Missing parameters.", status: 406}
    end
  end

  # private

  # def restrict_access
  #   api_key = User.find_by_secrete_key(params[:secrete_key])
  #   render json: { data: "Unauthorised", status: 401 } unless api_key
  # end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    # @bookings = Booking.all
    @rooms = Room.all
    @cat = Category.all
  end
  
  def show
  end

  def new
    @booking = Booking.new
  end

  def edit
  end

  def create
    @booking = Booking.new(booking_params)
    respond_to do |format|
      if @booking.save
        format.html { redirect_to bookings_path, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @bookings = Booking.all
    @cat = Category.all
    if @bookings.present?
      if @bookings
        ids = @bookings.pluck(:room_id)
        date1 = params[:start_date].to_date if params[:start_date].present?
        @start_date = date1.strftime("%Y %d %m") if date1.present?
        date2 = params[:end_date].to_date if params[:end_date].present?
        @end_date = date2.strftime("%Y %d %m") if date2.present?

        if params[:category_id].present? and params[:start_date].present? and params[:end_date].present?
          bookings = Booking.where("category_id = ? and start_date <= ? OR end_date >= ?", params[:category_id], @start_date,@end_date).pluck(:room_id)

          @rooms = Room.where("category_id = ?  and id NOT IN (?) ",params[:category_id],bookings)
        
        elsif params[:category_id].present? and params[:start_date].present? 
          
          bookings = Booking.where("category_id = ? OR start_date = ? ", params[:category_id], @start_date).pluck(:room_id)
          @rooms = Room.where("category_id = ?  and id NOT IN (?) ",params[:category_id],bookings)
        elsif params[:category_id].present? and params[:end_date].present? 
          
          bookings = Booking.where("category_id = ? OR end_date = ? ", params[:category_id], @end_date).pluck(:room_id)
          @rooms = Room.where("category_id = ?  and id NOT IN (?) ",params[:category_id],bookings)
        elsif params[:category_id].present? 
          @rooms = Room.where(category_id: params[:category_id])
        
        elsif params[:start_date].present?
           redirect_to request.referer, notice: 'Please Select End Date'
        elsif params[:end_date].present?
            redirect_to request.referer, notice: 'Please Select Start Date'
        else
          redirect_to request.referer, notice: 'Please Select Category Or Dates'
        end
      end
    else
      category = Category.find(params[:category_id])
      @rooms = category.rooms
    end
  end

  def book
    
  end

  def amount
    room = Room.find(params[:id])
    price = room.category.price
    @amount = price.to_i * params[:days].to_i
    render :json => {amount: @amount}
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:user_id, :room_id, :category_id, :start_date, :end_date, :amount, :full_name, :address, :phone_no)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for :booking, url: bookings_path do |f| %>
  
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name, class: "form-control", placeholder: " Full Name", required: :require %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, class: "form-control", placeholder: " Address", required: :require %>
  </div>
  <div class="field">
    <%= f.label :phone_no %><br>
    <%= f.text_field :phone_no, class: "form-control", placeholder: " Phone No", required: :require %>
  </div>
  <div class="field">
    <%#= f.label :user_id %><br>
    <%#= f.hidden_field_tag "user_id", current_user.id %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br>
    <%= text_field_tag :room_id, "", class: "form-control", readonly: true %>
    <%= f.hidden_field  :room_id %>

  </div>
  <%= f.hidden_field  :category_id %>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date, class: "form-control", id:'datepicker3' %>
    <!-- <div class='input-group date' id='datetimepicker3'>
      <input type='text' class="form-control" name="start_date" />
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div> -->
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date, class: "form-control", id:'datepicker4' %>
    <!-- <div class='input-group date' id='datetimepicker4'>
      <input type='text' class="form-control" name="end_date" />
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div> -->
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, class: "form-control", placeholder: " Amount", required: :require %>
  </div>
  

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript">
  

  $(function () {
    $("#datepicker3").datepicker({
      minDate: 0,
      maxDate: '+1Y+6M',
      onSelect: function (dateStr) {
          var min = $(this).datepicker('getDate'); // Get selected date
          $("#TextBox2").datepicker('option', 'minDate', min || '0'); // Set other min, default to today
      }
    });

    $("#datepicker4").datepicker({
        minDate: '0',
        maxDate: '+1Y+6M',
        onSelect: function (dateStr) {
            var max = $(this).datepicker('getDate'); // Get selected date
            $('#datepicker').datepicker('option', 'maxDate', max || '+1Y+6M'); // Set other max, default to +18 months
            var start = $("#datepicker3").datepicker("getDate");
            var end = $("#datepicker4").datepicker("getDate");
            var days = (end - start) / (1000 * 60 * 60 * 24);
            // $("#booking_amount").val(days);
            id = $("#booking_room_id").val();
            $.ajax({
              type: "GET",
              url: '/bookings/' + id + '/amount/?days='+ days,
              dataType: "json",
              success: function(data){
                  console.log('jhgdfsj')
                  $("#booking_amount").val(data['amount']);
                }

            });
        }
    });

    // $('#datetimepicker3').datetimepicker({
    //     format: "YYYY-MM-DD LT",
    //     sideBySide: true
    // });
    // $('#datetimepicker4').datetimepicker({
    //     format: "YYYY-MM-DD LT",
    //     sideBySide: true
    // });
  });
</script>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>
<div class="row">
  <div class="">
    <%= form_tag search_bookings_path, :method => 'get', :id => "room_search" do %>
        <div class="">
          <%= select_tag :category_id, options_from_collection_for_select(@cat, :id, :name), :prompt => "Select Category" , class: "form-control" %>
        <div>
        <div class='input-group date class=""' id='datetimepicker5'>
            <input type='text' class="form-control" name="start_date" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <div class='input-group date class=""' id='datetimepicker6'>
            <input type='text' class="form-control" name="end_date" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <div class="">
           <%= submit_tag "Search", :name => nil, class: "btn btn-success btn-search" %>
        </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% @rooms.each_slice(3) do |room| %>
    <% room.each do |r| %>
      <div class="rooms">
        <div class="room_pic">
          <%= image_tag r.room_pic.url %>
        </div>
        <div class="room_no">
          <%= r.floor %>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker5').datetimepicker({
            format: "YYYY-MM-DD LT",
            sideBySide: true
        });
        $('#datetimepicker6').datetimepicker({
            format: "YYYY-MM-DD LT",
            sideBySide: true
        });
    });
</script>


<style type="text/css">

</style>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Available Rooms Bookings</h1>


<div class="row">
  <div class="col-md-12">
    <% @rooms.each_slice(3) do |room| %>
    <% room.each do |r| %>
      <div class="rooms">
        <div class="room_pic">
          <%= image_tag r.room_pic.url %>
        </div>
        <div class="room_no">
          <%= r.floor %>
        </div>
        <div>
            <button type="button" class="btn btn-success book-room" data-id="<%= r.id %>" data-toggle="modal" data-target="#myModal"  data-name="<%= r.floor %>" data-category="<%= params[:category_id]%>">Book</button>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Hotel Booking</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "form" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    
  </div>
</div>


<script type="text/javascript">
    $(document).ready(function() {
        $('.book-room').click(function(){
            var id = $(this).data("id");
            var name = $(this).data("name");
            var category = $(this).data("category");
            $("#booking_room_id").val(id);
            $("#room_id").val(name);
            $("#booking_category_id").val(category);
        });
    });
   
</script>


<style type="text/css">
.rooms {
    width: 30%;
    border: 1px solid black;
    display: inline-block;
    padding: 15px;
    margin: 10px;
}
.room_pic img {
    width: 100%;
    max-height: 300px;
    min-height: 299px;
}
.room_no {
    text-align: center;
    font-size: 16px;
    font-weight: bold;
    padding-top: 20px;
}
</style>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @booking.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @booking.room_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @booking.end_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @booking.amount %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>